name: Sync main with type-effectiveness

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.Actions }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout type-effectiveness branch
        run: git checkout type-effectiveness

      - name: Configure Git user
        run: |
        git config --global user.email "EypoBot@github.com"
        git config --global user.name "EypoBot"

      - name: Merge main into type-effectiveness
        run: git merge main --no-ff --allow-unrelated-histories

      - name: Push changes
        run: git push origin type-effectiveness